services:
  nginx:
    image: nginx
    ports:
      - "8124:80"
    restart: "no"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-php
    restart: "no"
    volumes:
      - ./:/var/www/html/
  mariadb:
    image: mariadb:10.5
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "Europe/Prague"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db-dump:/db-dump
    ports:
      - "3310:3306"

volumes:
  mariadb-data:
